version: '3.8'

services:
  agent:
    extra_hosts: !reset [ ]
    environment:
      API_URL: "https://api.calculator.vingp.dev/"


  orchestrator:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculator-api.rule=Host(`api.calculator.vingp.dev`)"
      - "traefik.http.routers.calculator-api.entrypoints=http,https"
      - "traefik.http.routers.calculator-api.tls.certresolver=myresolver"
      - "traefik.http.services.calculator-api.loadbalancer.server.port=8080"
    networks:
      - traefik
    ports: !reset []


  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculator-web.rule=Host(`calculator.vingp.dev`)"
      - "traefik.http.routers.calculator-web.entrypoints=http,https"
      - "traefik.http.routers.calculator-web.tls.certresolver=myresolver"
      - "traefik.http.services.calculator-web.loadbalancer.server.port=80"

    networks:
      - traefik
    ports: !reset [ ]


networks:
  traefik:
    external: true

