version: '3.8'

services:

  orchestrator:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.schedule-api.rule=Host(`api.calculator.vingp.dev`)"
      - "traefik.http.routers.schedule-api.entrypoints=http,https"
      - "traefik.http.routers.schedule-api.tls.certresolver=myresolver"
      - "traefik.http.services.schedule-api.loadbalancer.server.port=80"
    networks:
      - traefik
    ports: !reset []

  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.schedule-api.rule=Host(`calculator.vingp.dev`)"
      - "traefik.http.routers.schedule-api.entrypoints=http,https"
      - "traefik.http.routers.schedule-api.tls.certresolver=myresolver"
      - "traefik.http.services.schedule-api.loadbalancer.server.port=80"

    networks:
      - traefik
    ports: !reset [ ]


networks:
  traefik:
    external: true