version: '3.8'

services:
  agent:
    extra_hosts: !reset [ ]

  orchestrator:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculator.rule=Host(`api.calculator.vingp.dev`)"
      - "traefik.http.routers.calculator.entrypoints=http,https"
      - "traefik.http.routers.calculator.tls.certresolver=myresolver"
      - "traefik.http.services.calculator.loadbalancer.server.port=8080"
    networks:
      - traefik
    ports: !reset []


  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculator.rule=Host(`calculator.vingp.dev`)"
      - "traefik.http.routers.calculator.entrypoints=http,https"
      - "traefik.http.routers.calculator.tls.certresolver=myresolver"
      - "traefik.http.services.calculator.loadbalancer.server.port=80"
    environment:
      ENV: "prod"
    networks:
      - traefik
    ports: !reset [ ]


networks:
  traefik:
    external: true

