version: '3.8'


services:
  agent:
    build: ./agent
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  orchestrator:
    build: ./orchestrator
    ports:
      - "8080:8080"
    restart: always

  web:
    build: ./web
    environment:
      ENV: "local"
    ports:
      - "80:80"
    restart: always


